openapi: 3.0.2
info:
  title: 'Online store'
  version: "0.1"
paths:
  /products/:
    get:
      operationId: ProductsList
      description: 'List of products'
      parameters: []
      responses:
        '200':
          content:
          application/json:
            schema:
              type: array
              items:
                  $ref: '#/components/schemas/Product'
          description: ''
      tags:
        - products

    post:
      operationId: ProductCreate
      description: 'Create product'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
      tags:
        - products

  /products/{id}:
    delete:
      operationId: ProductDelete
      description: 'Delete product'
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this products
          schema:
            type: string
      responses:
        '204':
          description: ''
      tags:
        - products

    put:
      operationId: ProductUpdate
      description: 'Product update'
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this product.
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Product'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
      tags:
        - products

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 64
      required:
        - name